apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-d # 設定 labels，讓 service 可透過 selector 選取
spec:
  replicas: 1 # 建立 1個 Pod
  # ReplicaSet 的效果套用在帶有 app = mysql 的 pod 上
  selector: # 此 Deployment 的規則要適用到哪些 Pod (即 template 中指定的 labels)
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template: # Pod 的定義
    metadata:
      labels: # 設定給 Pod 的 label
        app: mysql
    spec: # Pod 運行的 container
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
            # - name: MYSQL_ALLOW_EMPTY_PASSWORD
            #   value: 'true'
          # args: ["--default-authentication-plugin=mysql_native_password"] # mysql 8
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  selector:
    app: mysql
  ports:
      - port: 3306
        targetPort: 3306 # 指定 Pod 上允許外部資源存取 Port Number
        # nodePort: 3306 # 指定 Pod 上的 targetPort 要 mapping 到 Node 上的哪個 port